name = "clamav_client"
licences = ["GPL-3.0-only"]
description = "ClamAV client implementation in pure Gleam"

version = "1.0.2"

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
mug = ">= 1.2.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"