name: release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27.1.2"
          gleam-version: "1.6.2"
      - run: |
            gleam build
            gleam publish --yes
        env:
            HEXPM_USER: ${{ secrets.HEXPM_USER }}
            HEXPM_PASS: ${{ secrets.HEXPM_PASS }}