name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27.1.2"
          gleam-version: "1.6.2"
          rebar3-version: "3"
      - run: |
          docker pull clamav/clamav:latest
          CONTAINERID=$(docker run -d -p 3310:3310 -p 3310:3310/udp clamav/clamav:latest)

          echo ${CONTAINERID}

          while ! grep -q "socket found, clamd started" $(docker logs -n 5 ${CONTAINERID}); do
            echo "Waiting for ClamAV to start..."
            sleep 5
          done

          echo "ClamAV started successfully."

          gleam deps download
          gleam test
          gleam format --check src test